# Generated by Django 4.2.3 on 2023-09-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=20)),
                ('user_gmail', models.EmailField(max_length=30)),
                ('user_address', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserProblem_title', models.CharField(max_length=30)),
                ('UserProblem_description', models.CharField(max_length=50)),
                ('UserProblem_status', models.CharField(choices=[('solved', 'solved'), ('pending', 'pending'), ('uderprogress', 'underprogress')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserData.userdata')),
            ],
        ),
    ]
