# Generated by Django 4.2.3 on 2023-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblem',
            name='UserProblem_photo',
            field=models.ImageField(default='', upload_to='user/problemimage'),
        ),
    ]
