# Generated by Django 4.2.3 on 2023-09-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_userproblem_userproblem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblem',
            name='UserProblem_location',
            field=models.CharField(default='At LNCT University', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userproblem',
            name='UserProblem_description',
            field=models.CharField(max_length=100),
        ),
    ]
